services:
  mysql:
    image: mysql:8.2.0-oracle   # arm image (only oracle linux base)
    container_name: mysql
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - mysql-store:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "$MYSQL_DATABASE", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 5s

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      mysql:
        condition: service_healthy
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=3
      - PMA_HOSTS=mysql
      - PMA_USER=${MYSQL_DATABASE}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 8088:80
    healthcheck:
      test: ["CMD", "curl", "-m", "5", "http://localhost/"]
      interval: 15s
      timeout: 5s
      retries: 4
      start_period: 10s

volumes:
  mysql-store:
